cirruslabs/cirrus-ci-web

serve.json
src/Routes.tsx

Use `fa-code` as this is the source.
The duplicate GitHub icons look ugly together.

Change icon for cirrus-ci-web repository link

---

src/components/chips/TaskTransactionChip.tsx

Tell the user exactly when compute credit cost will be calculated.

Made the compute credit cost tooltip less confusing

---

public/index.html

User noticed:
> all pages on your site have this HTML tag on them: <link rel="canonical" href="https://cirrus-ci.com"/> -- that is definitely not how the tag is supposed to be used. It tells search engines that every page on your site is really aliases for your homepage (as in identical content), which they are not. It's probably not a huge deal, but it is likely hurting your site's SEO (search engine rankings) on various search engines.

Remove canonical link tag

---

src/components/CirrusFavicon.tsx

My optimizations PR broke the coloring of the favicon based on the build status, so this fixes it.

Fix favicon not updating

---

src/components/metrics/RepositoryMetricsPage.tsx

Ref: https://www.engadget.com/2016/06/13/os-x-is-now-macos/

fix: rename macOS

---

src/components/tasks/TaskDetails.tsx

This makes it possible to open the pull request directly from the task page (example task page: https://cirrus-ci.com/task/4778695107805184). Previously it was required to click on "View All Tasks" first and then on the branch link.

Link to branch in each detailed task view

---

src/components/metrics/RepositoryMetricsPage.tsx

Instead of the older `osx_instance`.

Matrics page: query metrics using the newer macos_instance

---

src/components/chips/TaskResourcesChip.tsx

Changes the color of the chip so that it doesn't blend in with the background of the chip.
It looked like this before:
Now the background of the icon is just black like a lot of the other chips.

Fix minor color issue

---

src/components/builds/BuildDetails.tsx
src/components/chips/BuildChangeChip.tsx
src/components/tasks/TaskDetails.tsx

...to that of used on GitHub and the Git's original [7-hexdigit default](https://github.com/git/git/commit/e6c587c733b4634030b353f4024794b08bc86892), so that <kbd>Ctrl+F</kbd> works for searching builds.

Increase short SHA size to 7 hexdigits

---

src/components/builds/ConfigurationWithIssues.tsx

Since now it's possible to have `WARNING`'s without `ERROR`'s.

ConfigurationWithIssues: context-dependent summary text

---

schema.graphql
src/components/chips/TaskCancellerChip.tsx
src/components/chips/TaskRerunnerChip.tsx
src/components/tasks/TaskDetails.tsx

Looks like this:
The chips are clickable.
Resolves https://github.com/cirruslabs/cirrus-ci-web/issues/375.

Display the user who re-ran or cancelled a task

---

src/components/tasks/TaskDetails.tsx

These labels are used internally to display a username chip (see #376), so they should be filtered out.
Resolves https://github.com/cirruslabs/cirrus-ci-web/issues/377.

Don't show labels with the user ID who cancelled or re-ran the tasks

---

src/components/tasks/TaskDetails.tsx

props.task.terminalCredential can be `null`

Regression: fixed NPE

---

src/components/logs/InlineLogs.tsx
src/components/tasks/TaskDebuggingInformation.tsx

An example of a task with no execution events and agent logs: http://cirrus-ci.com/task/5393919098748928.

InlineLogs: handle null values

---

src/scenes/Repository/GitHubRepository.tsx
src/scenes/Repository/Repository.tsx

After upgrade in #401 router no longer supported `/`. Proposed fix in 493c36e18ff945b77ab352195bc93ebe6a7304fb didn't actually fix the issue.
This change does fix the issue and resolves #413

Fixed branch routine

---

README.md
schema.graphql
src/components/account/ViewerBuildList.tsx
src/components/builds/BuildDetails.tsx
src/components/builds/LastDefaultBranchBuildMiniRow.tsx
src/components/builds/LastDefaultBranchBuildRow.tsx
src/components/common/CommitMessage.tsx
src/components/repositories/RepositoryBuildList.tsx
src/components/tasks/TaskDetails.tsx

Another thing that's been bugging me for a while :smile: 
Similar to how GitHub renders commit messages:
Made it so that bits of commit messages surrounded by backticks (`) are rendered as inline code:
This should be changed across the web interface, unless I accidentally missed a spot :P
In doing so, I refactored out a `CommitMessage` component for what was previously in `TaskDetails` & `BuildDetails` and also a `CommitTitle` component for everywhere else commit messages appear.

Simple "markdown" in commit messages

---

src/components/workers/PersistentWorkerPoolsList.tsx

...because it generates a double-nested `input` request object, which in turn results in the error described in https://github.com/cirruslabs/cirrus-ci-docs/issues/964.

No need to use PersistentWorkerPoolsListCreateMutationVariables

---

schema.gql
src/components/chips/BuildBranchNameChip.tsx

Related to https://github.com/cirruslabs/cirrus-ci-docs/issues/963
Here is a screenshot of how two builds will look like next to each other. One build is for a commit on a master branch and the second build is for a tag build.

Use a different icon for tag builds

---

src/components/tasks/TaskDetails.tsx

If a task is partially updated than the `executionInfo` and other stuff can be `null`. Let's play it smart and reuse the component query for the update.
Fixes #482

Update all the task details in subscription

---

src/components/builds/BuildsTable.tsx

Similar to how it was with `BuildBranchNameChip` before.

Use different icons for regular builds and tags in the new UI

---

schema.gql

Schema update

---

src/components/chips/BuildBranchNameChip.tsx
src/components/chips/BuildChangeChip.tsx
src/components/chips/HookCreatedChip.tsx
src/components/chips/HookStatusChip.tsx
src/components/chips/RepositoryNameChip.tsx
src/components/chips/RepositoryOwnerChip.tsx
src/components/chips/TaskNameChip.tsx
src/components/hooks/HookDetails.tsx
src/scenes/Hook/Hook.tsx

Move Hook and Hook Details components to Relay Hooks 

---

src/components/builds/BuildsTable.tsx
src/components/builds/CreateBuildDialog.tsx
src/components/chips/BuildStatusChip.tsx
src/components/repositories/RepositoryBuildList.tsx
src/scenes/Repository/Repository.tsx

Migration repository

---

src/components/builds/BuildDebuggingInformation.tsx
src/components/builds/BuildDetails.tsx
src/components/builds/ConfigurationWithIssues.tsx
src/components/chips/BuildCreatedChip.tsx
src/scenes/Build/BuildById.tsx
src/scenes/Build/BuildBySHA.tsx

Migration build by SHA

---

src/components/chips/TaskDurationChip.tsx
src/components/compute-credits/BillingSettingsButton.tsx
src/components/compute-credits/BillingSettingsDialog.tsx
src/components/compute-credits/ComputeCreditsBase.tsx
src/components/compute-credits/ComputeCreditsStripeDialog.tsx
src/components/compute-credits/OwnerComputeCredits.tsx
src/components/settings/OwnerSettings.tsx
src/scenes/Owner/OwnerSettingsRenderer.tsx

Migration owner settings

---

src/AllRoutes.tsx
src/components/account/AccountInformation.tsx
src/components/account/UserProfile.tsx
src/components/builds/LastDefaultBranchBuildMiniRow.tsx
src/components/chips/HookNameChip.tsx
src/components/common/AccountSwitch.tsx
src/components/tasks/TaskCommandList.tsx
src/components/tasks/TaskCommandLogs.tsx
src/scenes/Home/Home.tsx
src/scenes/Profile/ViewerProfile.tsx
src/scenes/Profile/ViewerTopRepositories.tsx

Migration of the remaining components 

---

src/AllRoutes.tsx
src/components/compute-credits/ComputeCreditsTransactionRow.tsx
src/components/hooks/HookListRow.tsx
src/components/settings/OwnerApiSettings.tsx
src/components/settings/OwnerPersistentWorkerPools.tsx
src/components/settings/OwnerScopedTokenDialog.tsx
src/components/settings/OwnerSecuredVariables.tsx
src/components/tasks/TaskListRow.tsx
src/components/webhooks/DeliveryInfoDialog.tsx
src/components/webhooks/DeliveryInfoDialogLazyContent.tsx
src/components/webhooks/DeliveryRow.tsx
src/scenes/Header/ActiveRepositoriesDrawer.tsx

Migration of the remaining components

---

src/utils/navigateHelper.ts

It seems Relay is not playing nice with react router navigation. Lets temporary disable it until we figure out the right way to integrate these two frameworks.

Disable React Router Navigation

---

src/components/logs/InlineLogs.tsx

before:
after:
Makes copying code from the UI cleaner.

prevent lineNumbers from appearing in selection when copying code

---

src/components/workers/WorkerStatusChip.tsx

Happens when deleting a worker, see CIRRUS-CI-WEB-C3 in Sentry for more details.
This is just a work around to fix it for now, the underlying cause is probably this: https://github.com/facebook/relay/issues/3514.

Fix NPE in WorkerStatusChip

---

src/components/compute-credits/MonthlyUsageChart.tsx

Initially these charts were showing only free usage but this didn't make sense, so we changed the data to be all the usage of the managed infrastructure. But the labels were not updated.

Fixed labels

---

package.json
src/components/logs/Logs.tsx
src/components/tasks/TaskCommandList.tsx
src/components/tasks/TaskCommandLogs.tsx
src/components/tasks/TaskDetails.tsx
src/mui.ts
yarn.lock

Looks like this by default for tasks that use `CIRRUS_LOG_TIMESTAMP`:
Looks like this when toggled for tasks that use `CIRRUS_LOG_TIMESTAMP`:
Not displayed for tasks that don't use `CIRRUS_LOG_TIMESTAMP`.
Resolves #581.

Add an option to strip timestamps when CIRRUS_LOG_TIMESTAMP is used

---

src/components/tasks/TaskDetails.tsx

Fix dark theme for "Display log timestamps"

---

src/components/chips/BuildBranchNameChipNew.tsx

Problem: when making a release, two builds are usually created, and it's hard to tell which of the builds will be the one having `$CIRRUS_TAG`, and thus, likely, a release task, which one might want to check on:
On the screenshot above, the only difference is the icon, and the icon name is `UnarchiveIcon`, which is kinda makes no sense.
Changing just the icon helps things a bit, but introduces some weirdness, because now have a *tag* signifier next to a *branch* name:
What works, though, IMO, is actually displaying the tag (when there's one), and this is what this PR does:
Now, it doesn't even matter which icon we'd pick, it's pretty evident what kind of Git reference we're dealing with.

Better differentiate branches and tags

---

Dockerfile
serve.json

When rolling out a new deployment requests like `/static/js/6848.e511c8953423.chunk.js` cab point to the default 200 of the `index.html` since it's an SPA. Then CDN cache cache it up for an hour which can break things.
This change disables caching by default and makes sure only static assets are actually cached.
Note that `serve` still returns `etag` so `index.html` will be "cached" but without a TTL.

Cache Tweaks

---

src/components/tasks/TaskDetails.tsx

To prevent scenarios where one can trigger `bar` without dependencies in the following example:
```yaml
foo_task:
trigger_type: manual
script: exit 0
bar_task:
depends_on: foo
script: exit 0
```

Allow to trigger only paused manual tasks

---

config-overrides.js
package.json
yarn.lock

Unfortunately, Yarn can't do this on its own (https://github.com/yarnpkg/yarn/issues/4986), so I've just removed the specific dependencies from the `yarn.lock` by hand and then re-ran the `yarn`.

yarn.lock: update dependencies

---

yarn.lock

The upgrade for "socks" is needed to remove the dependency on "ip" package, which is deprecated.

Upgrade "socks" and "ws" NPM packages

---

src/createRelayEnvironment.ts

Problem: currently we pass the `json()` promise to Relay, but this promise might as well turn into undefined if there's no JSON data in the response.
Solution: await on the json() before returning and propagate the exception if one is caught.
Related Sentry issue: `CIRRUS-CI-WEB-AK`.

Prevent "cannot read properties of undefined (reading 'data')" errors

---

package.json
src/components/builds/CreateBuildDialog.tsx
yarn.lock

It seems to be only used for syntax validation in JavaScript, JSON, PHP, CoffeeScript, CSS, XQuery modes, but we're using YAML mode.
Related Sentry issue: `CIRRUS-CI-WEB-AP`.

Disable Ace worker

---

package.json
src/components/cirrus-terminal/CirrusTerminal.ts
yarn.lock

With a high probability this should fix Sentry issue `CIRRUS-CI-WEB-BW`.
P.S. manually verified that the Cirrus Terminal is working.

Upgrade xterm.js

---

src/AllRoutes.tsx
src/cirrusTheme.ts
src/components/status/StatusFallback.tsx
src/components/tasks/TaskCommandList.tsx
src/components/tasks/TaskDetails.tsx
src/components/webhooks/DeliveryInfoDialog.tsx
src/scenes/Header/ActiveRepositoriesDrawerFallback.tsx

Basically what this does is wraps every `<Suspense>` in an `<Sentry.ErrorBoundary>` with the same fallback as `<Suspense>` has.
The result is that the UI doesn't break and fall into a blank page on error, but keeps pulsating:
[<video src="">](https://github.com/cirruslabs/cirrus-ci-web/assets/85709/16f09721-4cfc-4408-9771-a71a47d51728)

More granular error boundaries

---

src/components/chips/BuildStatusChipNew.tsx

If a build failed the red color will indicate attention already. But for partially completed aka with final paused tasks we should indicate the "call to action" so to speak.

Gray out only completed builds with paused tasks

---

package.json
src/createRelayEnvironment.ts
src/index.tsx
yarn.lock

Manually, because Dependabot can't create an update on its own.

Upgrade Sentry to version 8
