cirruslabs/cirrus-ci-web

src/scenes/Home/Home.js

I tried not to open this but it was too tempting
blame ocd

Add link to docs on homepage

---

src/scenes/Home/Home.js

@fkorotkov sorry for breaking it, I think this will fix it

Fix build?

---

package.json

Doesn't hurt to have this stuff

Add some package.json fields

---

public/index.html

Cool new SEO (twitter + facebook)

Add social media metadata

---

.cirrus.yml
yarn.lock

Lots of cool updates
sorry if this breaks stuff just trying to help

Bump dependencies

---

public/index.html

Add canonical URL

---

public/index.html
public/robots.txt
public/sitemap.xml
src/scenes/GitHub/GitHubOrganizationSettingsRenderer.js
src/scenes/Header/ViewerComponent.js
src/scenes/Home/Home.js
src/scenes/NotFound.js
src/scenes/Viewer/ViewerProfile.js
src/scenes/Viewer/ViewerTopRepositories.js

Improve SEO more

---

public/index.html

Fix broken link

---

public/manifest.json

Add name to manifest

---

public/index.html

Just noticed this, don't want it linking to another persons profile :o

Fix broken Twitter handle

---

src/components/LastDefaultBranchBuildMiniRow.js
src/components/LastDefaultBranchBuildRow.js
src/components/RepositoryBuildList.js
src/components/ViewerBuildList.js

Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/240

Fix markdown bug

---

package.json
src/cirrusTheme.js
src/components/TaskCommandList.js
src/components/TaskCommandLogs.js
src/components/logs/Logs.js
yarn.lock

Highlight Log Lines

---

package-lock.json

* Latest material UI builds
* update lodash (security fixes)
* Updated query-string (small bug fix)

[SECURITY] Dependency updates

---

src/scenes/Viewer/ViewerTopRepositories.js

Add space before word

---

package-lock.json

* Bump *`lodash.template`* from 0.4.0 to 0.5.0 **(Security fixes)**
* Updated other deps - (ONLY FOR BUG FIXES)

[Security] Bump dependencies

---

package-lock.json
package.json
schema.graphql
src/Routes.js
src/components/RepositoryBuildList.js
src/components/metrics/MetricsChart.js
src/components/metrics/RepositoryMetricsCharts.js
src/components/metrics/RepositoryMetricsPage.js
src/scenes/RepositoryMetrics/RepositoryMetrics.js
src/utils/time.js

Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/326

Expose Repository Metrics

---

src/components/TaskCommandLogs.tsx

Fix [Object object] issue

---

package.json
src/components/DurationTicker.tsx
src/components/TaskCommandList.tsx
src/utils/time.ts

those are 2 commits extracted from my other PR

Minor fixes

---

README.md
src/Routes.tsx

Some users are not aware of Cirrus CI Web being open sourced and that contributions are more than welcome. 😅
Also update ReadMe to mention how to auth from locally running front end.
cc @RDIL @geekflyer

Added GitHub Link

---

package-lock.json
package.json
schema.graphql
src/components/CreateBuildDialog.tsx

Adds placeholder, different config options, etc.

Change up build dialogue

---

public/robots.txt

Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/443

Fix indexing of tasks and builds

---

src/rtu/ConnectionManager.ts
src/vendor/reconnecting-websocket/reconnecting-websocket.js

Convert some functions to lambdas

---

package-lock.json

Fixes a sub-dependencies' dependencies' dependencies' dependencies' dependencies' dependency being insecure

Fixed security issue in dep tree

---

src/App.css
src/App.tsx
src/index.css

Makes webpack have to do less work

Merge together CSS

---

src/components/chips/TaskNameChip.tsx

Should be possible to select task using Vimium

---

tsconfig.json

Shouldn't have functional change, just nice to have

Changed typescript to use React JSX

---

src/components/TaskDetails.tsx
src/components/chips/TaskResourcesChip.tsx

Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/529
/cc @eksperimental

Show Task Resources

---

package-lock.json
package.json
src/Routes.tsx
src/components/explorer/ApiExplorer.tsx

Api Explorer

---

src/components/chips/NextCronInvocationTimeChip.tsx
src/components/repositories/RepositoryCronSettings.tsx
src/components/repositories/RepositorySettingsPage.tsx

Related to https://github.com/cirruslabs/cirrus-ci-docs/issues/39

Cron Settings UI

---

serve.json

Fixes potential clickjacking issues.

[Security] Avoid frames from external sources from loading

---

.github/dependabot.yml

Disable indirect dependencies

---

package-lock.json
package.json
public/index.html
schema.graphql
serve.json
src/components/artifacts/ArtifactsView.tsx
src/components/compute-credits/BillingSettingsDialog.tsx
src/components/explorer/ApiExplorer.tsx
src/components/tasks/TaskDetails.tsx

* React helmet types v6
* Remove jQuery/Bootstrap's JS - speeds up first-time-loads by a ton (I have confirmed it works just fine without it)
* Sync button colors in UI
* Avoid passing the router where possible (I benchmarked this, it saved a couple hundred milliseconds on the render of each page with a component that had the withRouter removed on)

Minor tweaks

---

schema.graphql
src/components/account/AccountInformation.tsx
src/components/account/UserProfile.tsx
src/components/artifacts/TaskArtifacts.tsx
src/components/chips/RepositoryNameChip.tsx
src/components/metrics/RepositoryMetricsCharts.tsx

So I finally understand the basics of relay, so as 'practice', I have looked through the components and have found some data being fetched that looks unused in the components it is being called in.
Because GQL is advertised as being the way to "only get what you need", this will most likely make the mini http requests smaller (and maybe faster)!
I'm still new to this so please let me know if I did something wrong.  
Signed-off-by: Reece Dunham <me@rdil.rocks>

Optimize graphql queries

---

schema.graphql
src/components/tasks/TaskCommandList.tsx

* MUI v5 changes `ExpansionPanel` -> `Accordion`, update as such
* Add names to the different actions (todo: possibly icons in the future?)
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/676
Signed-off-by: Reece Dunham <me@rdil.rocks>

Descriptive names on accordions

---

package-lock.json
package.json
schema.graphql
src/components/account/AccountInformation.tsx
src/components/chips/BuildCreatedChip.tsx
src/components/chips/TaskCreatedChip.tsx
src/components/chips/TaskExperimentalChip.tsx
src/components/chips/TaskNameChip.tsx
src/scenes/Home/Home.tsx
src/scenes/RepositoryMetrics/RepositoryMetrics.tsx

I'm going to do more of this later.  
Signed-off-by: Reece Dunham <me@rdil.rocks>

More classes to hooks

---

src/components/repositories/RepositoryCronSettings.tsx
src/components/repositories/RepositorySettings.tsx
src/components/repositories/RepositorySettingsPage.tsx

* To override `env` vars. Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/739
* Choose config resolution strategy. Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/662

Added new repository settings

---

schema.graphql
src/components/builds/BuildDetails.tsx
src/components/tasks/TaskDetails.tsx
src/components/tasks/TaskList.tsx
src/components/tasks/TaskListRow.tsx

Flame graph for tasks

---

package.json
src/Routes.tsx
src/components/account/AccountInformation.tsx
src/components/status/GCPStatus.tsx
src/components/status/GitHubStatus.tsx
yarn.lock

[Privacy Badger](https://privacybadger.org/) successfully saved me (by preventing me from connecting to cloud.google.com), so I fixed this side effect of the request failing.  Also minor styling tweaks.

Improve styles, avoid crashing

---

src/components/__tests__/Logs.test.tsx
src/components/logs/Logs.tsx
src/components/tasks/TaskCommandLogs.tsx

Generalize Logs Component

---

schema.graphql
src/components/builds/BuildDetails.tsx
src/components/builds/ConfigurationWithIssues.tsx

Rich parser errors

---

schema.graphql
src/Routes.tsx
src/components/chips/HookCreatedChip.tsx
src/components/chips/HookStatusChip.tsx
src/components/chips/TaskNameChip.tsx
src/components/common/CirrusFavicon.tsx
src/components/hooks/HookDetails.tsx
src/scenes/Hook/Hook.tsx
src/utils/colors.ts
src/utils/status.ts

Implement hooks page

---

src/components/builds/BuildDetails.tsx
src/components/builds/LastDefaultBranchBuildMiniRow.tsx
src/components/builds/LastDefaultBranchBuildRow.tsx
src/components/chips/BuildStatusChip.tsx
src/components/chips/TaskDurationChip.tsx
src/components/tasks/TaskDetails.tsx

Set missing useEffect() dependencies

---

src/components/builds/BuildDetails.tsx
src/components/chips/HookNameChip.tsx
src/components/hooks/HookList.tsx
src/components/hooks/HookListRow.tsx
src/components/tasks/TaskDetails.tsx
src/utils/navigate.ts

Build details page:
Task details page:
Resolves #356.

Hooks: display hooks on build and task pages

---

src/components/repositories/RepositoryBuildList.tsx
src/createRelayEnvironment.ts
src/rtu/ConnectionManager.ts

Live update builds on repository pages

---

src/components/tasks/TaskCommandList.tsx

Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/850.

Fix log line not expanding

---

schema.graphql
src/components/repositories/RepositorySettings.tsx

Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/379.

Settings: added a checkbox to invalidate caches

---

schema.graphql
src/Routes.tsx
src/components/builds/BuildDetails.tsx
src/components/hooks/HookDetails.tsx
src/components/hooks/HookList.tsx
src/components/hooks/HookListRow.tsx
src/components/tasks/TaskDetails.tsx
src/utils/navigate.ts

Things that still need to be implemented:
* hide old hooks
* make sure "View All Hooks" button opens up a build/task page with the "Hooks" tab already active

Hook page: view all hooks + rerun hook buttons

---

src/components/builds/BuildDetails.tsx
src/components/builds/DebuggingInformation.tsx

BuildDetails page: debugging information button

---

schema.graphql
src/components/builds/ConfigurationWithIssues.tsx

The closing touch to https://github.com/cirruslabs/cirrus-cli/issues/377.

ConfigurationWithIssues: filter out non-YAML issues

---

schema.graphql
src/components/repositories/RepositorySettings.tsx
src/components/tasks/TaskDetails.tsx

Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/851.

Granular cache invalidation

---

src/components/account/ViewerBuildList.tsx
src/components/builds/BuildDetails.tsx
src/components/builds/LastDefaultBranchBuildMiniRow.tsx
src/components/chips/RepositoryOwnerChip.tsx
src/components/hooks/HookDetails.tsx
src/components/tasks/TaskDetails.tsx

To ease navigation to the organization

Separate repository owner chip

---

src/components/tasks/TaskDetails.tsx

Hide Cirrus Terminal when the task enters final state

---

src/components/builds/BuildDetails.tsx
src/components/hooks/HookList.tsx
src/components/hooks/HookType.tsx
src/components/tasks/TaskDetails.tsx

Looks like this (the code example and the wording slightly change depending on whether it's a build or a task):
Resolves #385.

Always show hooks tab

---

package.json
schema.graphql
src/components/webhooks/WebHookSettings.tsx
yarn.lock

See https://github.com/cirruslabs/cirrus-ci-docs/issues/861.

WebHook settings page: allow setting secret token

---

src/components/builds/ConfigurationWithIssues.tsx

Resolves https://github.com/cirruslabs/cirrus-ci-web/issues/383.

Make .cirrus.star evaluation errors more obvious

---

src/components/hooks/HookDetails.tsx

Otherwise it looks like that always

Fixed hook info population

---

schema.graphql
src/components/hooks/HookDetails.tsx

Hooks: display environment variables used

---

src/components/repositories/RepositorySecuredVariables.tsx
src/components/settings/OrganizationSecuredVariables.tsx

Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/824.

Don't disable secured variable input

---

src/components/artifacts/ArtifactsView.tsx

Something that has always slightly annoyed me with the artifacts view 😄 
Not in a position to test any of this, so this is more of a feature request. Will try this out correctly this evening.

artifacts: add file size to files in artifacts view

---

src/components/builds/BuildDebuggingInformation.tsx
src/components/builds/BuildDetails.tsx
src/components/logs/InlineLogs.tsx
src/components/tasks/TaskDebuggingInformation.tsx
src/components/tasks/TaskDetails.tsx

Fixes cirruslabs/cirrus-ci-docs#402

Task debug information

---

.cirrus.yml
.dockerignore
Dockerfile

* Copy yarn files to docker container
* Add PR task for a deployment dry-run (so if the docker build fails, people notice)
* Update serve (none of the changes should actually make a difference here)

Fix deployment

---

src/components/builds/BuildDetails.tsx

Similarly to `TaskDetails.tsx`'s `Cancel` button.

BuildDetails: use Cancel pictogram for consistency's sake

---

schema.graphql
src/components/logs/InlineLogs.tsx
src/components/tasks/TaskDebuggingInformation.tsx
src/components/tasks/TaskDetails.tsx

Separate agent warnings

---

schema.gql
src/components/account/ViewerBuildList.tsx
src/scenes/Home/Home.tsx

This currently fails to build due to https://github.com/facebook/relay/pull/3810.
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/971.

Add ability to show only running builds in "Recent Builds"

---

src/components/common/MarkdownTypography.tsx

Resolves https://github.com/cirruslabs/cirrus-ci-web/issues/441.

Fix dark theme link colors

---

package.json
yarn.lock

Might fix the issue reported in https://github.com/cirruslabs/cirrus-ci-web/issues/446.

package.json: upgrade xterm to 4.18.0

---

src/components/builds/CreateBuildDialog.tsx
src/components/compute-credits/BillingSettingsDialog.tsx
src/components/compute-credits/ComputeCreditsStripeDialog.tsx
src/components/hooks/HookDetails.tsx
src/components/repositories/RepositoryCronSettings.tsx
src/components/repositories/RepositorySecuredVariables.tsx
src/components/repositories/RepositorySettings.tsx
src/components/settings/OwnerApiSettings.tsx
src/components/settings/OwnerScopedTokenDialog.tsx
src/components/settings/OwnerSecuredVariables.tsx
src/components/tasks/TaskDetails.tsx
src/components/workers/PersistentWorkerPoolsList.tsx
src/components/workers/PoolDetails.tsx

Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/1080

Dialog for generating scoped tokens

---

src/components/repositories/RepositoryDangerSettings.tsx
src/components/repositories/RepositorySettingsPage.tsx

Fixes #144
Will look like this (inspired by GH's UI):

Expose deleting of repositories

---

package.json
src/components/explorer/ApiExplorer.tsx
src/index.css
yarn.lock

Update API explorer

---

src/cirrusTheme.ts
src/components/builds/BuildsTable.tsx
src/components/chips/BuildStatusChipNew.tsx

Filled status 

---

src/components/account/OwnerRepositoryList.tsx
src/components/builds/BuildDetails.tsx
src/components/common/AppBreadcrumbs.tsx
src/components/metrics/RepositoryMetricsPage.tsx
src/components/repositories/RepositoryBuildList.tsx
src/components/repositories/RepositorySettingsPage.tsx
src/components/settings/OwnerSettings.tsx
src/components/tasks/TaskDetails.tsx
src/scenes/Build/BuildById.tsx
src/scenes/Build/BuildBySHA.tsx
src/scenes/Owner/OwnerSettingsRenderer.tsx
src/scenes/Repository/OwnerRepository.tsx
src/scenes/Repository/Repository.tsx
src/scenes/RepositoryMetrics/RepositoryMetrics.tsx
src/scenes/RepositorySettings/RepositorySettings.tsx
src/scenes/Task/Task.tsx

So it's easier to reason about and pass new data like one for #494

Move breadcrumbs to where `QueryRenderer`s are

---

src/App.tsx

Add environment provider container to app

---

schema.gql
src/components/chips/TaskStatusChipExtended.tsx
src/components/workers/PoolDetails.tsx
src/components/workers/WorkerStatusChip.tsx
src/scenes/Workers/PoolById.tsx

Migration pool

---

src/components/builds/BuildsTable.tsx

Prevent table layout overflowing

---

src/components/artifacts/ArtifactsView.tsx
src/components/artifacts/TaskArtifacts.tsx
src/components/tasks/TaskDetails.tsx

Fix artifacts downloading

---

src/components/metrics/RepositoryMetricsPage.tsx
src/scenes/RepositoryMetrics/RepositoryMetrics.tsx

Migration metrics

---

src/components/account/OwnerRepositoryList.tsx
src/components/builds/LastDefaultBranchBuildRow.tsx
src/scenes/Owner/Owner.tsx
src/scenes/Repository/OwnerRepository.tsx

Migration owner

---

src/components/chips/NextCronInvocationTimeChip.tsx
src/components/repositories/RepositoryCronSettings.tsx
src/components/repositories/RepositoryDangerSettings.tsx
src/components/repositories/RepositorySecuredVariables.tsx
src/components/repositories/RepositorySettings.tsx
src/components/repositories/RepositorySettingsPage.tsx
src/components/tasks/TaskDetails.tsx
src/scenes/RepositorySettings/RepositorySettings.tsx

Migration repository settings

---

src/components/compute-credits/ComputeCreditsStripeDialog.tsx

Fix layout of Buy Credits dialog 

---

src/components/compute-credits/ComputeCreditsBase.tsx
src/components/compute-credits/MonthlyUsageChart.tsx
src/components/settings/OwnerSettings.tsx
src/utils/colors.ts

Show monthly usage

---

schema.gql
src/components/webhooks/WebHookSettings.tsx
src/components/workers/PersistentWorkerPoolsList.tsx

New webhooks UI

---

src/components/builds/BuildDetails.tsx

It doesn't make sense to re-run all tasks including executing and skipped ones. Let's just re-run tasks that actually were executed and finished.

Re-run all finished tasks

---

.graphqlconfig
package.json
src/components/tasks/TaskDetails.tsx
yarn.lock

Looks like this:
Resolves #580.

Ability to re-run tasks with dependents/dependencies traversal

---

src/components/logs/Logs.tsx
yarn.lock

Example that is currently not working: https://cirrus-ci.com/task/5802904892735488?logs=clone#L197

Fix log scrolling (#L<...>)

---

src/components/chips/TaskRerunnerChip.tsx

"Re-ran by a user" -> "Re-run by a user"

---

src/scenes/Header/ActiveRepositoriesDrawer.tsx

Similarly to the example on MDN: https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe#examples
The change looks like this if we ignore the space:
```patch
diff --git a/src/scenes/Header/ActiveRepositoriesDrawer.tsx b/src/scenes/Header/ActiveRepositoriesDrawer.tsx
index 125c514..06b96e3 100644
--- a/src/scenes/Header/ActiveRepositoriesDrawer.tsx
+++ b/src/scenes/Header/ActiveRepositoriesDrawer.tsx
@@ -43,13 +43,11 @@ function RegisterServiceWorkerIfNeeded(userId: string, webPushServerKey: string)
}
askNotificationPermission().then(permissionResult => {
-    navigator.serviceWorker
-      .register('/notification-service-worker.js')
-      .catch(function (err) {
+    navigator.serviceWorker.register('/notification-service-worker.js').catch(err => {
console.error('Unable …
```

Delay subscription manipulation until a service worker is active

---

yarn.lock

Manually upgrade `serialize-javascript`
